# -*- coding: utf-8 -*-
"""Copy of test2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jwyoMnSSCl-RnKFn0sOxjOwe4EU9nOP2
"""

# Importing required libraries

import pandas as pd
import numpy as np

# Reading the customer churn dataset

customer_data = pd.read_excel(
    "customer_churn_prediction_data.xlsx"
)

# Display first 5 records

customer_data.head()

# Checking dataset size

print("Dataset Shape:")
print(customer_data.shape)

# Display all column names

print("\nColumns:")
print(customer_data.columns)

# Display data types

print("\nData Types:")
print(customer_data.dtypes)

import matplotlib.pyplot as plt
import seaborn as sns

# Checking for missing values

customer_data.isnull().sum()

# Filling missing numerical values with mean

for column in customer_data.select_dtypes(include=np.number).columns:
    customer_data[column] = customer_data[column].fillna(
        customer_data[column].mean()
    )

# Filling missing categorical values with Unknown

for column in customer_data.select_dtypes(include="object").columns:
    customer_data[column] = customer_data[column].fillna(
        "Unknown"
    )

print("Missing values handled successfully.")

# Removing duplicate rows

customer_data.drop_duplicates(inplace=True)

print("Duplicate records removed successfully.")

# Check missing values again

customer_data.isnull().sum()

# Statistical summary of numerical data

customer_data.describe()

# Average age of customers

customer_data["Age"].mean()

# Average monthly charges

customer_data["MonthlyCharges"].mean()

# Highest monthly charge

customer_data["MonthlyCharges"].max()

# Lowest monthly charge

customer_data["MonthlyCharges"].min()

# Creating yearly charges column

customer_data["YearlyCharges"] = (
    customer_data["MonthlyCharges"] * 12
)

customer_data.head()

# Customers who left the company

churned_customers = customer_data[
    customer_data["Churn"] == 1
]

churned_customers.head()

# Customers who stayed with the company

active_customers = customer_data[
    customer_data["Churn"] == 0
]

active_customers.head()

# Count of churned and active customers

customer_data["Churn"].value_counts()

plt.figure(figsize=(6,4))

sns.countplot(
    x="Churn",
    data=customer_data,
    palette="Set2"
)

plt.title("Customer Churn Distribution")
plt.xlabel("Churn (0=Active, 1=Left)")
plt.ylabel("Number of Customers")
plt.show()

# Top 10 customers by total spending

customer_data.nlargest(
    10,
    "TotalSpend"
)

# Top 10 customers with lowest spending

customer_data.nsmallest(
    10,
    "TotalSpend"
)

import matplotlib.pyplot as plt
import seaborn as sns

top_10_spending = customer_data.nlargest(
    10,
    "TotalSpend"
)

plt.figure(figsize=(10,5))

sns.barplot(
    x=top_10_spending.index.astype(str),
    y=top_10_spending["TotalSpend"],
    palette="Greens_r"
)

plt.title("Top 10 Customers by Spending")
plt.xlabel("Customer")
plt.ylabel("Total Spend")

plt.show()

# Sorting customers from highest to lowest monthly charges

customer_data.sort_values(
    by="MonthlyCharges",
    ascending=False
)

import matplotlib.pyplot as plt
import seaborn as sns

low_10_spending = customer_data.nsmallest(
    10,
    "TotalSpend"
)

plt.figure(figsize=(10,5))

sns.barplot(
    x=low_10_spending.index.astype(str),
    y=low_10_spending["TotalSpend"],
    palette="Reds_r"
)

plt.title("Lowest 10 Customers by Spending")
plt.xlabel("Customer")
plt.ylabel("Total Spend")

plt.show()

# Convert MonthlyCharges column into NumPy array

monthly_charges = np.array(
    customer_data["MonthlyCharges"]
)

monthly_charges

# Average monthly charges

np.mean(monthly_charges)

# Median monthly charges

np.median(monthly_charges)

# Standard deviation of monthly charges

np.std(monthly_charges)

# Highest charge

np.max(monthly_charges)

# Lowest charge

np.min(monthly_charges)

import numpy as np
print(np.__version__)

# Average customer tenure

customer_data["TenureMonths"].mean()

# Count customers by internet service type

customer_data["InternetService"].value_counts()

import matplotlib.pyplot as mplt

# Count customers by payment method

customer_data["PaymentMethod"].value_counts()

# Count customers by contract type

customer_data["ContractType"].value_counts()

# Saving cleaned dataset

customer_data.to_excel(
    "cleaned_customer_churn_prediction_data.xlsx",
    index=False
)

print("Dataset saved successfully.")
